### 1. **Operaciones Básicas**

#### 1.1 Creación de Tensores
En PyTorch, crear un tensor es el primer paso para manejar datos. Estas funciones permiten definir y estructurar datos de acuerdo con nuestras necesidades.

1. **`torch.tensor(data)`**
   - Crea un tensor a partir de datos de entrada, que pueden ser listas, listas anidadas (para tensores multidimensionales) o arreglos NumPy.
   - **Ejemplo**:
     ```python
     import torch
     tensor = torch.tensor([1, 2, 3])
     print(tensor)  # tensor([1, 2, 3])

     tensor_multi = torch.tensor([[1, 2], [3, 4]])
     print(tensor_multi)
     # tensor([[1, 2],
     #         [3, 4]])
     ```

2. **`torch.zeros(size)`**
   - Crea un tensor lleno de ceros. Su tamaño se define por el argumento `size`, que puede ser un entero o una tupla de enteros.
   - **Ejemplo**:
     ```python
     zeros_tensor = torch.zeros(3)
     print(zeros_tensor)  # tensor([0., 0., 0.])

     zeros_matrix = torch.zeros((2, 3))
     print(zeros_matrix)
     # tensor([[0., 0., 0.],
     #         [0., 0., 0.]])
     ```

3. **`torch.ones(size)`**
   - Similar a `torch.zeros()`, pero crea un tensor lleno de unos.
   - **Ejemplo**:
     ```python
     ones_tensor = torch.ones(4)
     print(ones_tensor)  # tensor([1., 1., 1., 1.])

     ones_matrix = torch.ones((3, 3))
     print(ones_matrix)
     # tensor([[1., 1., 1.],
     #         [1., 1., 1.],
     #         [1., 1., 1.]])
     ```

4. **`torch.arange(start, end, step)`**
   - Crea un tensor que contiene una secuencia de valores, desde `start` hasta `end` (sin incluirlo), con un intervalo de `step`.
   - **Ejemplo**:
     ```python
     arange_tensor = torch.arange(0, 10, 2)
     print(arange_tensor)  # tensor([0, 2, 4, 6, 8])
     ```

5. **`torch.linspace(start, end, steps)`**
   - Genera un tensor de `steps` elementos, distribuidos linealmente entre `start` y `end`.
   - **Ejemplo**:
     ```python
     linspace_tensor = torch.linspace(0, 1, 5)
     print(linspace_tensor)  # tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
     ```

6. **`torch.rand(size)`**
   - Crea un tensor con valores aleatorios entre 0 y 1.
   - **Ejemplo**:
     ```python
     random_tensor = torch.rand((2, 2))
     print(random_tensor)
     # tensor([[0.4577, 0.9371],
     #         [0.1294, 0.9645]])
     ```

7. **`torch.randn(size)`**
   - Crea un tensor de valores aleatorios con una distribución normal (media 0, desviación estándar 1).
   - **Ejemplo**:
     ```python
     randomn_tensor = torch.randn(3)
     print(randomn_tensor)  # tensor([ 0.0736, -0.8794,  1.5635])
     ```

Estas funciones te permiten crear tensores iniciales, fundamentales para definir el tipo de datos que utilizarás en tus cálculos y modelos.

#### 1.2 Aritmética Básica
PyTorch permite realizar operaciones aritméticas básicas entre tensores y con escalares. Veamos las operaciones de suma, resta, multiplicación y división.

1. **Suma (`+` o `torch.add(tensor1, tensor2)`)**
   - Puedes sumar dos tensores de las mismas dimensiones o un tensor y un escalar.
   - **Ejemplo**:
     ```python
     tensor_a = torch.tensor([1, 2, 3])
     tensor_b = torch.tensor([4, 5, 6])

     sum_tensor = tensor_a + tensor_b
     print(sum_tensor)  # tensor([5, 7, 9])

     scalar_sum = tensor_a + 10
     print(scalar_sum)  # tensor([11, 12, 13])
     ```

2. **Resta (`-` o `torch.sub(tensor1, tensor2)`)**
   - Puedes restar dos tensores o un tensor y un escalar.
   - **Ejemplo**:
     ```python
     diff_tensor = tensor_a - tensor_b
     print(diff_tensor)  # tensor([-3, -3, -3])

     scalar_diff = tensor_a - 5
     print(scalar_diff)  # tensor([-4, -3, -2])
     ```

3. **Multiplicación (`*` o `torch.mul(tensor1, tensor2)`)**
   - Multiplica elemento a elemento dos tensores o un tensor y un escalar.
   - **Ejemplo**:
     ```python
     prod_tensor = tensor_a * tensor_b
     print(prod_tensor)  # tensor([ 4, 10, 18])

     scalar_prod = tensor_a * 2
     print(scalar_prod)  # tensor([2, 4, 6])
     ```

4. **División (`/` o `torch.div(tensor1, tensor2)`)**
   - Divide elemento a elemento dos tensores o un tensor y un escalar.
   - **Ejemplo**:
     ```python
     div_tensor = tensor_a / tensor_b
     print(div_tensor)  # tensor([0.2500, 0.4000, 0.5000])

     scalar_div = tensor_a / 2
     print(scalar_div)  # tensor([0.5000, 1.0000, 1.5000])
     ```

Estas operaciones permiten hacer cálculos directos y se usan de manera constante en el trabajo con redes neuronales, ya que forman la base para calcular las actualizaciones de parámetros y las funciones de error.

#### 1.3 Reducciones Simples
Las operaciones de reducción sirven para resumir un tensor a través de alguna operación, como suma o promedio.

1. **Suma de elementos (`torch.sum(tensor)`)**
   - Calcula la suma de todos los elementos de un tensor.
   - **Ejemplo**:
     ```python
     sum_elements = torch.sum(tensor_a)
     print(sum_elements)  # tensor(6)
     ```

2. **Promedio (`torch.mean(tensor)`)**
   - Calcula el promedio de todos los elementos.
   - **Ejemplo**:
     ```python
     mean_elements = torch.mean(tensor_a.float())  # convierte a float si es int
     print(mean_elements)  # tensor(2.0000)
     ```

3. **Mínimo (`torch.min(tensor)`)**
   - Devuelve el valor mínimo del tensor.
   - **Ejemplo**:
     ```python
     min_element = torch.min(tensor_a)
     print(min_element)  # tensor(1)
     ```

4. **Máximo (`torch.max(tensor)`)**
   - Devuelve el valor máximo del tensor.
   - **Ejemplo**:
     ```python
     max_element = torch.max(tensor_a)
     print(max_element)  # tensor(3)
     ```

#### 1.4 Comparaciones
Las comparaciones en PyTorch te permiten comparar elemento a elemento en los tensores y devolver valores de verdad.

1. **Igualdad (`torch.eq(tensor1, tensor2)`)**
   - Compara cada elemento y devuelve un tensor con `True` o `False`.
   - **Ejemplo**:
     ```python
     eq_tensor = torch.eq(tensor_a, tensor_b)
     print(eq_tensor)  # tensor([False, False, False])
     ```

2. **Mayor que (`torch.gt(tensor1, tensor2)`)**
   - Devuelve `True` donde los elementos en `tensor1` son mayores que en `tensor2`.
   - **Ejemplo**:
     ```python
     gt_tensor = torch.gt(tensor_a, tensor_b)
     print(gt_tensor)  # tensor([False, False, False])
     ```


## Relación de numpy y Pytorch
```python
import torch
import numpy as np

# Create a PyTorch tensor
pytorch_tensor = torch.tensor([1, 2, 3, 4, 5])

# Convert to NumPy array
numpy_array = pytorch_tensor.numpy()

print("PyTorch Tensor:", pytorch_tensor)
print("NumPy Array:", numpy_array)
print("Type:", type(numpy_array)) 
```

In [2]:
import os
print(os.environ['CONDA_DEFAULT_ENV'])

rrnn


In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])
print(tensor)  # tensor([1, 2, 3])


tensor([1, 2, 3])


In [36]:
import torch
import random
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
torch.randint(1, 21,(3,))

tensor([ 3,  8, 17])

In [37]:
torch.cuda.is_available()

False

In [41]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

tensor = torch.tensor([1, 2, 3],device=device)
tensor.device


device(type='mps', index=0)