### Resolución de los Ejercicios

#### 1. **Reshape y Manipulación de Dimensiones**

- **Ejercicio 1**

   ```python
   #tensor = torch.rand(3,3)
   tensor = torch.arange(9).reshape(3, 3)
   tensor_reshaped = torch.reshape(tensor, (1, 9))
   print("Tensor reshape (3x3 a 1x9):\n", tensor_reshaped)
   ```

- **Ejercicio 2**

   ```python
   tensor = torch.rand(5, 1, 5)
   tensor_squeezed = torch.squeeze(tensor)
   print("Tensor squeeze (5x1x5 a 5x5):\n", tensor_squeezed)
   ```

#### 2. **Concatenación y Combinación**

- **Ejercicio 3**

   ```python
   tensor1 = torch.rand(3, 2)
   tensor2 = torch.rand(3, 2)
   concatenated = torch.cat((tensor1, tensor2), dim=0)
   print("Tensores concatenados en dim 0:\n", concatenated)
   ```

- **Ejercicio 4**

   ```python
   tensor = torch.rand(10, 3)
   chunks = torch.chunk(tensor, 5, dim=0)
   print("Tensor dividido en 5 partes:\n", chunks)
   ```

#### 3. **Permutación y Transposición**

- **Ejercicio 5**

   ```python
   tensor = torch.rand(3, 4)
   transposed = torch.transpose(tensor, 0, 1)
   print("Tensor transpuesto (3x4 a 4x3):\n", transposed)
   ```

- **Ejercicio 6**

   ```python
   tensor = torch.rand(2, 3, 4)
   permuted = torch.permute(tensor, (2, 0, 1))
   print("Tensor permutado (2x3x4 a 4x2x3):\n", permuted)
   ```

#### 4. **Reducciones Avanzadas**

- **Ejercicio 7**

   ```python
   tensor = torch.rand(2, 3)
   product = torch.prod(tensor)
   print("Producto de todos los elementos:", product)
   ```

- **Ejercicio 8**

   ```python
   tensor = torch.rand(4, 4)
   cumsum_dim1 = torch.cumsum(tensor, dim=1)
   print("Suma acumulativa en dim 1:\n", cumsum_dim1)
   ```

#### 5. **Lógica Avanzada**

- **Ejercicio 9**

   ```python
   tensor1 = torch.rand(3, 3)
   tensor2 = torch.rand(3, 3)
   result = torch.where(tensor1 > tensor2, tensor1, tensor2)
   print("Valores mayores entre ambos tensores:\n", result)
   ```

- **Ejercicio 10**

   ```python
   tensor = torch.rand(5)
   selected = torch.masked_select(tensor, tensor > 0.5)
   print("Valores mayores que 0.5:\n", selected)
   ```

#### 6. **Broadcasting y Expansión**

- **Ejercicio 11**

   ```python
   tensor = torch.rand(5)
   tensor = tensor.unsqueeze(1)  # Ahora será de forma [5,1]
   expanded_tensor = tensor.expand(5, 3)
   print("Tensor expandido a 5x3:\n", expanded_tensor)
   ```

- **Ejercicio 12**

   ```python
   tensor = torch.rand(2, 1, 4)
   expanded_tensor= tensor.expand(2, 3, 4)
   print("Tensor expandido a 2x3x4:\n", expanded_tensor)
   ```

#### 7. **Aleatoriedad y Semillas**

- **Ejercicio 13**

   ```python
   torch.manual_seed(0)
   tensor = torch.rand(3, 3)
   print("Tensor con semilla establecida:\n", tensor)
   ```

- **Ejercicio 14**

   ```python
   tensor_probs = torch.rand(4)
   bernoulli_tensor = torch.bernoulli(tensor_probs)
   print("Muestra binaria usando bernoulli:\n", bernoulli_tensor)
   ```

1. **Ejercicio 15**

   ```python
   tensor = torch.rand(3, 3)
   expanded_tensor = tensor.expand(3, 3, 3)
   product_cum = torch.cumprod(expanded_tensor, dim=0)
   print("Tensor expandido a 3x3x3:\n", expanded_tensor)
   print("Producto acumulativo de todos los elementos:\n", product_cum)
   ```

2. **Ejercicio 16**

   ```python
   tensor_a = torch.rand(4, 4)
   tensor_b = torch.rand(4, 4)
   concatenated = torch.cat((tensor_a, tensor_b), dim=0)
   max_columna, _ = torch.max(concatenated, dim=0)
   print("Tensores concatenados en dim 0:\n", concatenated)
   print("Máximo de cada columna:\n", max_columna)
   ```

3. **Ejercicio 17**

   ```python
   tensor = torch.rand(3, 5)
   transposed_tensor = torch.transpose(tensor, 0, 1)
   suma_acumulativa = torch.cumsum(transposed_tensor, dim=1)
   print("Tensor transpuesto (3x5 a 5x3):\n", transposed_tensor)
   print("Suma acumulativa en nueva dim 1:\n", suma_acumulativa)
   ```

4. **Ejercicio 18**

   ```python
   torch.manual_seed(1)
   tensor_a = torch.rand(2, 2)
   tensor_b = torch.rand(2, 2)
   selected = torch.where(tensor_a > tensor_b, tensor_a, tensor_b)
   print("Tensor A:\n", tensor_a)
   print("Tensor B:\n", tensor_b)
   print("Valores seleccionados mayores entre ambos:\n", selected)
   ```

5. **Ejercicio 19**

   ```python
   tensor = torch.rand(4, 2)
   unsqueezed_tensor = torch.unsqueeze(tensor, 1)
   flattened_tensor = unsqueezed_tensor.view(-1)
   print("Tensor con nueva dimensión añadida:\n", unsqueezed_tensor)
   print("Tensor aplanado:\n", flattened_tensor)
   ```

6. **Ejercicio 20**

   ```python
   tensor = torch.rand(6, 2)
   parts = torch.split(tensor, 2, dim=0)
   means = torch.tensor([torch.mean(part) for part in parts])
   expanded_means = means.expand(6, 2)
   print("Partes divididas del tensor:\n", parts)
   print("Promedios de cada parte:", means)
   print("Promedios expandidos:\n", expanded_means)
   ```

7. **Ejercicio 21**

   ```python
   tensor = torch.rand(3, 4)
   permuted_tensor = torch.permute(tensor, (1, 0))
   mean_rows = torch.mean(permuted_tensor, dim=1)
   print("Tensor permutado (3x4 a 4x3):\n", permuted_tensor)
   print("Media de cada fila en nueva disposición:\n", mean_rows)
   ```

8. **Ejercicio 22**

   ```python
   tensor = torch.rand(5, 5)
   expanded_tensor = tensor.unsqueeze(1)
   masked_values = torch.masked_select(expanded_tensor, expanded_tensor > 0.7)
   print("Tensor con nueva dimensión añadida:\n", expanded_tensor)
   print("Valores mayores a 0.7:\n", masked_values)
   ```

9. **Ejercicio 23**

   ```python
   torch.manual_seed(42)
   tensor = torch.rand(3, 3)
   diagonal_sum = torch.sum(tensor.diagonal())
   print("Tensor generado con semilla establecida:\n", tensor)
   print("Suma de los elementos de la diagonal principal:", diagonal_sum)
   ```

10. **Ejercicio 24**

    ```python
    tensor = torch.rand(2, 3)
    unsqueezed_tensor = torch.unsqueeze(tensor, 1)
    suma_acumulativa = torch.cumsum(unsqueezed_tensor, dim=2)
    print("Tensor con dimensión añadida:\n", unsqueezed_tensor)
    print("Suma acumulativa en la última dimensión:\n", suma_acumulativa)
    ```


In [29]:
import torch
tensor1 = torch.rand(3, 2)
tensor2 = torch.rand(3, 2)
concatenated = torch.cat((tensor1, tensor2), dim=1)
print("tensor1: ",tensor1)
print("Tensor2: ",tensor2)
print("Tensores concatenados en dim 0:\n", concatenated)

tensor1:  tensor([[0.7456, 0.2722],
        [0.5943, 0.6131],
        [0.9728, 0.1258]])
Tensor2:  tensor([[0.9222, 0.7676],
        [0.1549, 0.2294],
        [0.5866, 0.8707]])
Tensores concatenados en dim 0:
 tensor([[0.7456, 0.2722, 0.9222, 0.7676],
        [0.5943, 0.6131, 0.1549, 0.2294],
        [0.9728, 0.1258, 0.5866, 0.8707]])


In [30]:
tensor = torch.rand(3, 4)
transposed = torch.transpose(tensor, 0, 1)
print("Tensor transpuesto (3x4 a 4x3):\n", transposed)

Tensor transpuesto (3x4 a 4x3):
 tensor([[0.7559, 0.8947, 0.9187],
        [0.3241, 0.7125, 0.1178],
        [0.1024, 0.9101, 0.9046],
        [0.6542, 0.7919, 0.5206]])


In [31]:
tensor.T

tensor([[0.7559, 0.8947, 0.9187],
        [0.3241, 0.7125, 0.1178],
        [0.1024, 0.9101, 0.9046],
        [0.6542, 0.7919, 0.5206]])

In [32]:
tensor = torch.rand(5)
selected = torch.masked_select(tensor, tensor > 0.5)
print("Valores mayores que 0.5:\n", selected)

Valores mayores que 0.5:
 tensor([0.6876, 0.9327, 0.7871, 0.9206])


In [ ]:
tensor = torch.rand(5)
tensor = tensor.unsqueeze(1)  
expanded_tensor = tensor.expand(5, 3)
print("Tensor expandido a 5x3:\n", expanded_tensor)


RuntimeError: The expanded size of the tensor (3) must match the existing size (5) at non-singleton dimension 1.  Target sizes: [5, 3].  Tensor sizes: [5]

In [47]:
tensor = torch.rand(3)
tensor = tensor.unsqueeze(1)  
expanded_tensor = tensor.expand(3, 4)
product_cum = torch.cumprod(expanded_tensor, dim=0)
print("Tensor expandido a 3x3x3:\n", expanded_tensor)
print("Producto acumulativo de todos los elementos:\n", product_cum)

Tensor expandido a 3x3x3:
 tensor([[0.1250, 0.1250, 0.1250, 0.1250],
        [0.5706, 0.5706, 0.5706, 0.5706],
        [0.1807, 0.1807, 0.1807, 0.1807]])
Producto acumulativo de todos los elementos:
 tensor([[0.1250, 0.1250, 0.1250, 0.1250],
        [0.0713, 0.0713, 0.0713, 0.0713],
        [0.0129, 0.0129, 0.0129, 0.0129]])


In [52]:
tensor = torch.rand(4, 2)
unsqueezed_tensor = torch.unsqueeze(tensor, 1)
flattened_tensor = unsqueezed_tensor.flatten()
print("Tensor con nueva dimensión añadida:\n", unsqueezed_tensor)
print("Tensor aplanado:\n", flattened_tensor)

Tensor con nueva dimensión añadida:
 tensor([[[0.5592, 0.2682]],

        [[0.6708, 0.0404]],

        [[0.1923, 0.7824]],

        [[0.0669, 0.8079]]])
Tensor aplanado:
 tensor([0.5592, 0.2682, 0.6708, 0.0404, 0.1923, 0.7824, 0.0669, 0.8079])
