### 2. **Operaciones Intermedias**

#### 2.1 Reshape y Manipulación de Dimensiones
Estas operaciones son fundamentales para estructurar y reorganizar tensores, especialmente en redes neuronales, donde los datos deben tener dimensiones específicas.

1. **`torch.reshape(tensor, shape)`**
   - Cambia la forma del tensor a la especificada en `shape` sin alterar sus datos.
   - **Ejemplo**:
     ```python
     tensor = torch.tensor([1, 2, 3, 4, 5, 6])
     reshaped_tensor = torch.reshape(tensor, (2, 3))
     print(reshaped_tensor)
     # tensor([[1, 2, 3],
     #         [4, 5, 6]])
     ```

2. **`torch.view(shape)`**
   - Similar a `reshape`, pero requiere que el tensor original esté en un bloque contiguo de memoria. Es útil para hacer conversiones rápidas sin copiar datos.
   - **Ejemplo**:
     ```python
     view_tensor = tensor.view(2, 3)
     print(view_tensor)
     # tensor([[1, 2, 3],
     #         [4, 5, 6]])
     ```

3. **`torch.squeeze(tensor, dim)`**
   - Elimina dimensiones de tamaño 1 del tensor. `dim` es opcional y permite especificar qué dimensión eliminar.
   - **Ejemplo**:
     ```python
     tensor = torch.tensor([[[1], [2]], [[3], [4]]])
     squeezed_tensor = torch.squeeze(tensor)
     print(squeezed_tensor)
     # tensor([[1, 2],
     #         [3, 4]])
     ```

4. **`torch.unsqueeze(tensor, dim)`**
   - Añade una dimensión de tamaño 1 en la posición `dim`.
   - **Ejemplo**:
     ```python
     unsqueezed_tensor = torch.unsqueeze(tensor, 0)
     print(unsqueezed_tensor)
     # tensor([[[[1], [2]], [[3], [4]]]])
     ```

Estas operaciones son especialmente útiles para modificar las dimensiones de entrada en modelos y facilitar el procesamiento en lotes (batches).

#### 2.2 Concatenación y Combinación
Permiten unir tensores de manera flexible y dividirlos en partes para procesamiento.

1. **`torch.cat(tensors, dim)`**
   - Concatena una secuencia de tensores a lo largo de una dimensión específica.
   - **Ejemplo**:
     ```python
     tensor_a = torch.tensor([[1, 2], [3, 4]])
     tensor_b = torch.tensor([[5, 6]])
     cat_tensor = torch.cat((tensor_a, tensor_b), dim=0)
     print(cat_tensor)
     # tensor([[1, 2],
     #         [3, 4],
     #         [5, 6]])
     ```

2. **`torch.stack(tensors, dim)`**
   - Apila una secuencia de tensores a lo largo de una nueva dimensión. Útil cuando se necesitan múltiples tensores con una nueva dimensión añadida.
   - **Ejemplo**:
     ```python
     stacked_tensor = torch.stack((tensor_a, tensor_b.expand_as(tensor_a)), dim=1)
     print(stacked_tensor)
     # tensor([[[1, 2], [5, 6]],
     #         [[3, 4], [5, 6]]])
     ```

3. **`torch.split(tensor, split_size_or_sections, dim)`**
   - Divide un tensor en partes, especificando el tamaño de cada parte o una lista de tamaños.
   - **Ejemplo**:
     ```python
     tensor = torch.tensor([1, 2, 3, 4, 5, 6])
     split_tensor = torch.split(tensor, 2)
     for t in split_tensor:
         print(t)
     # tensor([1, 2])
     # tensor([3, 4])
     # tensor([5, 6])
     ```

4. **`torch.chunk(tensor, chunks, dim)`**
   - Divide un tensor en partes iguales según el número de `chunks`.
   - **Ejemplo**:
     ```python
     chunk_tensor = torch.chunk(tensor, 3)
     for t in chunk_tensor:
         print(t)
     # tensor([1, 2])
     # tensor([3, 4])
     # tensor([5, 6])
     ```

Estas operaciones son esenciales para organizar los datos de entrada en redes neuronales, ajustándolos para procesamiento en paralelo o en lotes.

#### 2.3 Permutación y Transposición
Cambian la disposición de las dimensiones de un tensor, fundamental para operaciones que requieren formas específicas en sus datos.

1. **`torch.transpose(tensor, dim0, dim1)`**
   - Intercambia dos dimensiones en un tensor.
   - **Ejemplo**:
     ```python
     tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
     transposed_tensor = torch.transpose(tensor, 0, 1)
     print(transposed_tensor)
     # tensor([[1, 4],
     #         [2, 5],
     #         [3, 6]])
     ```

2. **`torch.permute(tensor, dims)`**
   - Reorganiza las dimensiones según el orden especificado en `dims`. Es más flexible que `transpose` para tensores de varias dimensiones.
   - **Ejemplo**:
     ```python
     tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
     permuted_tensor = torch.permute(tensor, (2, 0, 1))
     print(permuted_tensor)
     # tensor([[[1, 3],
     #          [5, 7]],
     #         [[2, 4],
     #          [6, 8]]])
     ```

La permutación es fundamental para redes neuronales convolucionales, donde las dimensiones del tensor de entrada se reorganizan para una correcta aplicación de filtros.

#### 2.4 Reducciones Avanzadas
Estas reducciones avanzadas te permiten realizar análisis detallado de datos y estadísticas.

1. **`torch.prod(tensor)`**
   - Calcula el producto de todos los elementos.
   - **Ejemplo**:
     ```python
     tensor = torch.tensor([1, 2, 3, 4])
     prod = torch.prod(tensor)
     print(prod)  # tensor(24)
     ```

2. **`torch.cumsum(tensor, dim)`**
   - Calcula la suma acumulativa a lo largo de una dimensión.
   - **Ejemplo**:
     ```python
     cumsum_tensor = torch.cumsum(tensor, dim=0)
     print(cumsum_tensor)  # tensor([1, 3, 6, 10])
     ```

3. **`torch.cumprod(tensor, dim)`**
   - Calcula el producto acumulativo a lo largo de una dimensión.
   - **Ejemplo**:
     ```python
     cumprod_tensor = torch.cumprod(tensor, dim=0)
     print(cumprod_tensor)  # tensor([1, 2, 6, 24])
     ```

4. **`torch.argmin(tensor)`**
   - Devuelve el índice del valor mínimo en el tensor.
   - **Ejemplo**:
     ```python
     tensor = torch.tensor([3, 1, 4, 0, 2])
     min_index = torch.argmin(tensor)
     print(min_index)  # tensor(3)
     ```

5. **`torch.argmax(tensor)`**
   - Devuelve el índice del valor máximo en el tensor.
   - **Ejemplo**:
     ```python
     max_index = torch.argmax(tensor)
     print(max_index)  # tensor(2)
     ```

Estas reducciones permiten resumir datos rápidamente y realizar cálculos que optimizan la eficiencia en redes neuronales, como encontrar valores extremos o acumulados.

#### 2.5 Lógica Avanzada
Este grupo de operaciones permite realizar selecciones y condiciones complejas.

1. **`torch.where(condition, x, y)`**
   - Devuelve elementos de `x` donde `condition` es `True`, y de `y` donde es `False`.
   - **Ejemplo**:
     ```python
     condition = torch.tensor([True, False, True, False])
     x = torch.tensor([1, 2, 3, 4])
     y = torch.tensor([10, 20, 30, 40])
     result = torch.where(condition, x, y)
     print(result)  # tensor([ 1, 20,  3, 40])
     ```

2. **`torch.masked_select(tensor, mask)`**
   - Selecciona elementos de un tensor donde `mask` es `True`.
   - **Ejemplo**:
     ```python
     tensor = torch.tensor([1, 2, 3, 4, 5])
     mask = tensor > 3
     selected_elements = torch.masked_select(tensor, mask)
     print(selected_elements)  # tensor([4, 5])
     ```

Estas operaciones son útiles para filtrar y condicionar datos en procesamiento de redes neuronales, permit

iendo seleccionar solo los valores relevantes.

#### 2.6 Broadcasting
PyTorch soporta broadcasting de forma automática, pero `expand()` y `expand_as()` son útiles para controlar cómo se hace.

1. **`tensor.expand(*sizes)`**
   - Expande un tensor para que coincida con las dimensiones `sizes`. Esto no copia los datos, sino que reutiliza los valores del tensor original.
   - **Ejemplo**:
     ```python
     tensor = torch.tensor([1, 2, 3])
     expanded_tensor = tensor.expand(2, 3)
     print(expanded_tensor)
     # tensor([[1, 2, 3],
     #         [1, 2, 3]])
     ```

2. **`tensor.expand_as(other_tensor)`**
   - Expande el tensor para que coincida con la forma de `other_tensor`.
   - **Ejemplo**:
     ```python
     other_tensor = torch.zeros((2, 3))
     expanded_tensor = tensor.expand_as(other_tensor)
     print(expanded_tensor)
     # tensor([[1, 2, 3],
     #         [1, 2, 3]])
     ```
