### 1. **Broadcasting en PyTorch**
Broadcasting es una técnica que permite realizar operaciones aritméticas en tensores de dimensiones diferentes. PyTorch aplica reglas específicas para "expandir" dimensiones de manera automática, lo que permite combinar tensores de diferentes formas en una misma operación sin necesidad de ajustar sus dimensiones manualmente.

#### Reglas del Broadcasting
1. **Comparación de dimensiones**: PyTorch comienza a comparar dimensiones de derecha a izquierda.
2. **Dimensiones iguales**: Si dos dimensiones son iguales, no se requiere broadcasting.
3. **Dimensión igual a 1**: Una dimensión de tamaño 1 puede expandirse para igualar la otra dimensión (por ejemplo, un tensor de forma `[3, 1]` puede combinarse con uno de forma `[3, 4]`).
4. **Dimensiones faltantes**: Si un tensor tiene menos dimensiones, se considerará que las dimensiones faltantes son de tamaño 1 en la operación.

#### Ejemplos Prácticos
Supongamos que tenemos dos tensores de diferentes formas:

```python
import torch

# Tensor de forma [3, 1]
tensor_a = torch.tensor([[1], [2], [3]])

# Tensor de forma [1, 4]
tensor_b = torch.tensor([[1, 2, 3, 4]])
```

Si sumamos `tensor_a` y `tensor_b`, PyTorch expandirá automáticamente las dimensiones de cada tensor para que coincidan:

```python
result = tensor_a + tensor_b
print(result)
# tensor([[2, 3, 4, 5],
#         [3, 4, 5, 6],
#         [4, 5, 6, 7]])
```

En este caso:
- `tensor_a` se expande de `[3, 1]` a `[3, 4]`, repitiendo el valor en la segunda dimensión.
- `tensor_b` se expande de `[1, 4]` a `[3, 4]`, repitiendo el valor en la primera dimensión.

Este tipo de expansión se realiza en memoria sin duplicar los datos físicamente, haciendo las operaciones más eficientes.

#### Funciones `expand()` y `expand_as()`
A veces, es útil definir explícitamente el broadcasting, y para esto usamos `expand()` y `expand_as()`.

- **`expand(sizes)`**: Permite especificar las dimensiones a las cuales debe expandirse un tensor.
  ```python
  expanded_tensor = tensor_a.expand(3, 4)
  print(expanded_tensor)
  # tensor([[1, 1, 1, 1],
  #         [2, 2, 2, 2],
  #         [3, 3, 3, 3]])
  ```

- **`expand_as(tensor)`**: Expande un tensor para que coincida en forma con otro tensor.
  ```python
  expanded_tensor_as = tensor_a.expand_as(result)
  print(expanded_tensor_as)
  # tensor([[1, 1, 1, 1],
  #         [2, 2, 2, 2],
  #         [3, 3, 3, 3]])
  ```

El broadcasting facilita la manipulación de tensores en redes neuronales al evitar el ajuste manual de dimensiones, especialmente en tareas como la combinación de vectores y matrices de tamaño variable.

---

### 2. **Descomposición en Valores Singulares (SVD)**
La Descomposición en Valores Singulares es una técnica en álgebra lineal que descompone una matriz \( A \) en tres matrices: \( U \), \( S \) y \( V^T \), donde:

- \( U \) y \( V^T \) son matrices ortogonales.
- \( S \) es una matriz diagonal que contiene los valores singulares.

Esta técnica es útil en tareas de reducción de dimensionalidad, compresión de datos, y análisis de características en redes neuronales.

#### Ejemplo Práctico
Consideremos una matriz sencilla:

```python
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
U, S, V = torch.svd(matrix)
```

En este caso:
- `U` contiene los vectores ortogonales de la matriz original.
- `S` contiene los valores singulares (en forma de vector).
- `V` contiene los vectores ortogonales de la transpuesta.

```python
print("U:\n", U)
print("S:\n", S)
print("V:\n", V)
```

### Propiedades de SVD
1. **Reconstrucción de la Matriz**: La matriz original puede reconstruirse como `U * diag(S) * V^T`.
2. **Reducción de Dimensionalidad**: Los valores más altos de `S` suelen contener la mayor parte de la información, permitiendo reducir la matriz eliminando los valores más pequeños.
3. **Aplicaciones en Redes Neuronales**: La SVD es útil para optimizar redes neuronales grandes, identificar redundancias y reducir el tamaño de modelos complejos.

---

### 3. **Distribuciones en PyTorch**
Sí, PyTorch permite generar varias distribuciones directamente con su módulo `torch.distributions`, aunque la librería `numpy` también es una buena opción. PyTorch soporta diversas distribuciones, y el uso de este módulo permite mantener los datos en tensores de PyTorch, lo que facilita su uso en modelos de redes neuronales.

#### Distribuciones Comunes en PyTorch
1. **Distribución Normal (Gaussiana)**
   ```python
   from torch.distributions import Normal

   normal_dist = Normal(0, 1)  # media=0, desviación estándar=1
   sample = normal_dist.sample((5,))  # 5 muestras
   print(sample)
   ```

2. **Distribución Bernoulli**
   - Modela experimentos binarios con probabilidad `p`.
   ```python
   from torch.distributions import Bernoulli

   bernoulli_dist = Bernoulli(torch.tensor([0.7, 0.2]))
   sample = bernoulli_dist.sample((3,))  # 3 muestras
   print(sample)
   ```

3. **Distribución Poisson**
   - Modela la frecuencia de eventos en intervalos de tiempo con tasa `lambda`.
   ```python
   from torch.distributions import Poisson

   poisson_dist = Poisson(2.0)  # tasa lambda=2
   sample = poisson_dist.sample((5,))
   print(sample)
   ```

4. **Distribución Uniforme**
   - Distribuye valores aleatorios en un rango entre `low` y `high`.
   ```python
   from torch.distributions import Uniform

   uniform_dist = Uniform(0, 10)
   sample = uniform_dist.sample((3,))
   print(sample)
   ```

#### Ventajas de Usar PyTorch sobre NumPy
- **Compatibilidad**: Las muestras generadas en `torch.distributions` son tensores de PyTorch, lo que facilita su integración en modelos sin necesidad de conversión.
- **Soporte de Gradientes**: Las distribuciones de PyTorch pueden usarse en redes neuronales con gradientes, siendo compatibles con el sistema autograd para tareas de optimización.